### ISSUE TITLE
Does not override Image or Host variables anymore

### ISSUE THREAD

**Issue by kjq** [quarkiverse/quarkus-helm#135]
With the recent upgrade to 0.2.0 the variables `host` and `image` are not being interpolated anymore using a custom value. 

The standard Kubernetes manifest is generated correctly and does override these variables

The specific values in question are `image` and `host` (`version` works fine):
```yaml
"2":
          property: host
          paths: (kind == Ingress).spec.rules.host
          value: ${MY_HOST:localhost}
 "4":
          property: image
          paths: (kind == Deployment).spec.template.spec.containers.image
          value: ${quarkus.container-image.registry:<REGISTRY>}/${quarkus.container-image.group:<GROUP>}/${quarkus.container-image.name:<NAME>}:${quarkus.container-image.tag:latest}
"5":
          property: version
          paths: "*.metadata.labels.'app.kubernetes.io/version'"
          value: ${MY_VERSION:${my_project.version}}

```

If I "manually" export these as ENV variables (i.e. `QUARKUS_CONTAINER_IMAGE_REGISTRY`) I can replicate the issue locally with the same results. This is how our CI/CD job applies the variables when generating the helm chart.

Further testing with ENV and custom variables in the application.yaml look to work.  This recognizes the ENV `MY_VERSION` or if I use a custom variable.
```yaml
property: version
paths: "*.metadata.labels.'app.kubernetes.io/version'"
value: ${MY_VERSION:${my_project.version}}
```

Oddly, if i do something like this, the bottom one gets the correct value:

```yaml
"4":
  property: image
  paths: (kind == Deployment).spec.template.spec.containers.image
  value: ${quarkus.container-image.registry:<REGISTRY>}/${quarkus.container-image.group:<GROUP>}/${quarkus.container-image.name:<NAME>}:${quarkus.container-image.tag:latest}
"5":
  property: version
  paths: "*.metadata.labels.'app.kubernetes.io/version'"
  value: ${quarkus.container-image.registry:<REGISTRY>}/${quarkus.container-image.group:<GROUP>}/${quarkus.container-image.name:<NAME>}:${quarkus.container-image.tag:latest}
```

Finally, this does not work - it is falling back to whatever the "quarkus" expected value would be.
```yaml
property: image
paths: (kind == Deployment).spec.template.spec.containers.image
value: "aaa"
```

If I use the regular `quarkus.kubernetes.ingress.host` variable, and do not use a custom value to override it, it seems to work for host but I cannot get image to be recognized. In all cases, the regular Kubernetes yaml works fine.
