### ISSUE TITLE
settings of quarkus.container-image not added correctly to values.yaml

### ISSUE THREAD

**Issue by wgresshoff** [quarkiverse/quarkus-helm#153]
Hello,
in my application.yml I don't set the image name explicitely but let it built by the container-image (jib) extension:
```
quarkus:
  container-image:
    build: true
    push: true
    group: wwu-ulb
    name: memoryalpha-to-inveniordm
    registry: harbor.uni-muenster.de
    username: xyz
```
In the generated kubernetes manifest the image name is set correctly to `harbor.uni-muenster.de/wwu-ulb/memoryalpha-to-inveniordm:1.0.0` but in the `values.yaml` group and registry settings are not respected:
```
app:
  ...
  image: gressho/memoryalpha-to-inveniordm:1.0.0
```
