### ISSUE TITLE
camelCasing the property names in values.yaml is problematic

### ISSUE THREAD

**Issue by wgresshoff** [quarkiverse/quarkus-helm#154]
Hi,
I have the following use case:
Our Kubernetes cluster has a gatekeeper installed which rejects every manifests without definition of resources, but not only `cpu` and `memory`, but also `ephemeral-storage`. In my `application.yml` I expose it like this:
```
quarkus:
  helm:
    values:
...
      5:
        property: database.primary.resources.limits.ephemeral-storage
        value: 0Mi
```
Which is added to `values.yaml` like this:
```
database:
  primary:
    resources:
      limits:
        ephemeralStorage: 0Mi
```
Using the bitnami chart to deploy a Postgresql DB leads in this case to a problem, as it just copies over the values from `values.yaml` to the manifest which can't be deployed as Kubernetes won't accept `ephemeralStorage`.
