### ISSUE TITLE
Sort the values generated within the file: ./target/helm/kubernetes/primaza-app/values.yaml

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-helm#201]
## Enhancement

The YAML values created within the file  ./target/helm/kubernetes/primaza-app/values.yaml are not sorted

```
app:
  serviceType: ClusterIP
  livenessProbe:
  ...
  image: cmoullia/primaza-app:0.0.1-SNAPSHOT
  readinessProbe:
  ...
  envs:
    github:
      repo: ""
    database:
      service:
        name: ""
    git:
      sha:
        commit: ""
    QUARKUS_DATASOURCE_USERNAME: user
    log:
      level: ""
    VAULT_URL: vault.127.0.0.1.nip.io
    QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://primaza-app-db:5432/primaza_database
    VAULT_PWD: sinclair
    QUARKUS_DATASOURCE_PASSWORD: pwd
    VAULT_USER: bob
    DB_SERVICE_NAME: primaza-app-db
db:
  auth:
    database: primaza_database
    password: pwd
    username: user
```
By consequence, that will be really to document them using a tool such as https://github.com/norwoodj/helm-docs and its github action equivalent: https://github.com/shaybentk/helm-docs-action/tree/main.

This is why I propose to enhance the existing generation mechanism to sort the values

```
app:
  envs:
    database:
      service:
        name: ""
    DB_SERVICE_NAME: primaza-app-db
    git:
      sha:
        commit: ""
    github:
      repo: ""
    log:
      level: ""
    QUARKUS_DATASOURCE_USERNAME: user
    QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://primaza-app-db:5432/primaza_database
    QUARKUS_DATASOURCE_PASSWORD: pwd
    VAULT_URL: vault.127.0.0.1.nip.io
    VAULT_USER: bob
    VAULT_PWD: sinclair
  image: cmoullia/primaza-app:0.0.1-SNAPSHOT
  livenessProbe:
  readinessProbe:
  serviceType: ClusterIP
db:
  auth:
    database: primaza_database
    password: pwd
    username: user
```
