### ISSUE TITLE
Use the configuration from the generated `values.yaml` in the application.properties

### ISSUE THREAD

**Issue by Sgitario** [quarkiverse/quarkus-helm#207]
For example, having the generated `values.yaml` file:

```yaml
db:
  auth:
    database: fruits_database
    password: pwd
    username: user
```

I would like to use these properties directly in the `application.properties` file:

```
quarkus.datasource.username=${db.auth.username}
quarkus.datasource.password=${db.auth.password}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_SERVICE_NAME:fruits-app-db}:5432/${db.auth.database}
```
