### ISSUE TITLE
Support unprefixed properties

### ISSUE THREAD

**Issue by Sgitario** [quarkiverse/quarkus-helm#209]
At the moment, the values provided via configuration can only be added under either the application root model (default `app`) or a dependency (either the name or the alias). Example:

```yaml
app:
  myProperty: aa
```

We could add the option to add properties in the generated `values.yaml` which are unprefixed:

```yaml
app:
  myProperty: aa
unprefixedProperty: bb
```
