### ISSUE TITLE
Helm values.schema.json validation not working with boolean and numeric env vars types

### ISSUE THREAD

**Issue by ThoSap** [quarkiverse/quarkus-helm#261]
Hi,

first of all I'm using Quarkus **`3.1.2.Final`** and Quarkiverse Helm **`1.0.8`**.
For the configuration file, I'm not using `application.properties`, but `application.yml` (https://quarkus.io/guides/config-yaml).

Today I wanted to make a clean configuration for the new `values.schema.json` file, for example for the Quarkus runtime property `QUARKUS_MAILER_PORT`.
As this is a port number, the type must be an integer and must be between `0` (or `1` as `0` is a reserved port) and `65535`.

As boolean and numeric types **must** be quoted for K8s Pod environment variables, I added the following workaround with an expression
```properties
# Specifiy the env var for the Deployment
quarkus.kubernetes.env.vars.QUARKUS_MAILER_PORT=${quarkus.mailer.port}

# Fix the quoting (https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#pipelines), else we get the error message below
quarkus.helm.expressions.QUARKUS_MAILER_PORT.path=(kind == Deployment).spec.template.spec.containers.(name == my-container).env.(name == QUARKUS_MAILER_PORT).value
quarkus.helm.expressions.QUARKUS_MAILER_PORT.expression={{ .Values.app.envs.MAIL_FOLDER_MAIL | quote }}
```
If we do not add this workaround, the Helm deploy or the K8s Deployment fails with

```go
Deployment in version "v1" cannot be handled as a Deployment:
  json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string

// OR

Deployment in version "v1" cannot be handled as a Deployment:
  json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```

For the Helm values.schema.json validation, I added the following properties
```properties
quarkus.helm.values-schema.properties.QUARKUS_MAILER_PORT.name=app.envs.QUARKUS_MAILER_PORT
quarkus.helm.values-schema.properties.QUARKUS_MAILER_PORT.type=integer
quarkus.helm.values-schema.properties.QUARKUS_MAILER_PORT.minimum=1
quarkus.helm.values-schema.properties.QUARKUS_MAILER_PORT.maximum=65535
```
but no matter what I try, the value in the values.yaml is always generated as a string
```yaml
---
app:
  envs:
    QUARKUS_MAILER_PORT: "25"
# The rest of the YAML was removed for brevity
```
therefore, the schema Helm `values.schema.json` validation fails with
![image](https://github.com/quarkiverse/quarkus-helm/assets/6555967/4becfc36-141e-4cbd-9838-bce98d1839fe)
when I want to deploy the Helm instance.

In my YAML `application.yml` instead of `application.properties` the K8s/Helm configuration is configured as follows (many unrelated properties are missing in this example for brevity):
```yaml
quarkus:
  kubernetes:
    env:
      vars:
        # Quarkus Mailer
        QUARKUS_MAILER_HOST: ${quarkus.mailer.host}
        QUARKUS_MAILER_PORT: ${quarkus.mailer.port}
        QUARKUS_MAILER_FROM: ${quarkus.mailer.from}
  helm:
    values-schema:
      properties:
        QUARKUS_MAILER_PORT:
          name: app.envs.QUARKUS_MAILER_PORT
          type: integer
          minimum: 1
          maximum: 65535
    expressions:
      QUARKUS_MAILER_PORT:
        path: (kind == Deployment).spec.template.spec.containers.(name == my-container).env.(name == QUARKUS_MAILER_PORT).value
        expression: "{{ .Values.app.envs.QUARKUS_MAILER_PORT | quote }}"
```
