### ISSUE TITLE
Probes are using the first port which is not consistent with the generated manifest or settings

### ISSUE THREAD

**Issue by kjq** [quarkiverse/quarkus-helm#269]
It looks like the Helm generated "probes" are using the wrong (first) port listed in the manifest. This varies across multiple projects during the same build - some will work (because it is `http` first) and others will not (because it is `https` first).

In the Kubernetes configuration (same across _all_ services):
```yaml
kubernetes:
      deployment-target: kubernetes
      liveness-probe:
        http-action-port-name: http
      ports:
        http:
          path: /blah
      readiness-probe:
        http-action-port-name: http
      startup-probe:
        http-action-port-name: http
```

Generated using the Helm extension (wrong) it takes the _first_ defined `ports`.  Running the same build across multiple projects, if that first port is `http` then it is right...

```yaml
livenessProbe:
  failureThreshold: {{ .Values.helm.livenessProbe.failureThreshold }}
  httpGet:
    path: {{ .Values.helm.livenessProbe.httpGet.path }}
    port: {{ .Values.helm.ports.https }}
    scheme: {{ .Values.helm.livenessProbe.httpGet.scheme }}
ports:
  - containerPort: {{ .Values.helm.ports.https }}
    name: https
    protocol: TCP
  - containerPort: {{ .Values.helm.ports.http }}
    name: http
    protocol: TCP
readinessProbe:
  failureThreshold: {{ .Values.helm.readinessProbe.failureThreshold }}
  httpGet:
    path: {{ .Values.helm.readinessProbe.httpGet.path }}
    port: {{ .Values.helm.ports.https }}
    scheme: {{ .Values.helm.readinessProbe.httpGet.scheme }}
startupProbe:
  failureThreshold: {{ .Values.helm.startupProbe.failureThreshold }}
  httpGet:
    path: {{ .Values.helm.startupProbe.httpGet.path }}
    port: {{ .Values.helm.ports.https }}
    scheme: {{ .Values.helm.startupProbe.httpGet.scheme }}
```

Here is an example from the **same build** where the first port is `http` and it is correct:

```yaml
ports:
  - containerPort: {{ .Values.helm.ports.http }}
    name: http
    protocol: TCP
  - containerPort: {{ .Values.helm.ports.https }}
    name: https
    protocol: TCP
readinessProbe:
  failureThreshold: {{ .Values.helm.readinessProbe.failureThreshold }}
  httpGet:
    path: {{ .Values.helm.readinessProbe.httpGet.path }}
    port: {{ .Values.helm.ports.http }}
    scheme: {{ .Values.helm.readinessProbe.httpGet.scheme }}
```

The regular Kubernetes generated manifest (Quarkus) is always correct:
```yaml
livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

Running multiple times in a row demonstrates the issue.

As a workaround this seems to work for now:
```yaml
        "port":
          path: "(kind == Deployment).spec.template.spec.containers.*.httpGet.port"
          expression: "{{ .Values.helm.ports.http }}"
```
