### ISSUE TITLE
Two consecutive `mvn package` corrupt the generated files

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#30]
If I run two consecutive `mvn package` because I have changed my `application.properties`  then my `values.yaml` get corrupted:

First iteration:

```
---
examplesQuarkusHelm:
  image: pagonzal/examples-quarkus-helm:1.2.1.Beta1-SNAPSHOT
  host: examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
```

Second iteration
```
---
examplesQuarkusHelm:
  image: pagonzal/examples-quarkus-helm:1.2.1.Beta1-SNAPSHOT
  host: examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
---
examplesQuarkusHelm:
  image: pagonzal/examples-quarkus-helm:1.2.1.Beta1-SNAPSHOT
  host: examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
```

Same with the rest of the generated files: deployment.yaml, ingress.yaml, services.yaml, chart.yaml and values.yaml

Workaround: `mvn clean package`
