### ISSUE TITLE
Quotes in src/main/helm/values.yaml get arbitrarily dropped in target/heml/openshift/*/values.yaml

### ISSUE THREAD

**Issue by yrodiere** [quarkiverse/quarkus-helm#315]
If I have this in `src/main/helm/values.yaml`: 

```yaml
opensearch:
  limits:
    cpu: 2000m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 2Gi
  java-opts: "-Xms1g -Xmx1g"
```

Then the resulting file at `target/heml/openshift/*/values.yaml` doesn't have quotes around the java options (see last line), and is therefore invalid:

```yaml
---
app:
  [...]
opensearch:
  limits:
    cpu: 2000m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 2Gi
  java-opts: -Xms1g -Xmx1g
```

Workaround: insert a space before the `-`:

```yaml
opensearch:
  limits:
    cpu: 2000m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 2Gi
  java-opts: " -Xms1g -Xmx1g"
```

Then the file will be syntactically correct, at least:

```yaml
---
app:
  [...]
opensearch:
  limits:
    cpu: 2000m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 2Gi
  java-opts: ' -Xms1g -Xmx1g'
```
