### ISSUE TITLE
Helm Release Name and Namespace

### ISSUE THREAD

**Issue by ThoSap** [quarkiverse/quarkus-helm#334]
I have the following use case.
I have multiple deployments of the same service with different configurations, which automtically should use the selected Helm K8s release namespace (`.Release.Namespace`) and Helm release name (`.Release.Name`).

For this I added the following Quarkus Helm expressions:
```
quarkus:
  helm:
    expressions:
      releaseNamespace1:
        expression: "{{ .Release.Namespace }}"
        path: metadata.namespace
      releaseNamespace2:
        expression: "{{ .Release.Namespace }}"
        path: (kind == Deployment).spec.template.metadata.namespace
      releaseInstanceName1:
        expression: "{{ .Release.Name }}"
        path: metadata.name
      releaseInstanceName2:
        expression: "{{ .Release.Name }}"
        path: metadata.labels.'app.kubernetes.io/name'
      releaseInstanceName3:
        expression: "{{ .Release.Name }}"
        path: (kind == Service).spec.selector.'app.kubernetes.io/name'
      releaseInstanceName4:
        expression: "{{ .Release.Name }}"
        path: (kind == Deployment).spec.selector.matchLabels.'app.kubernetes.io/name'
      releaseInstanceName5:
        expression: "{{ .Release.Name }}"
        path: (kind == Deployment).spec.template.metadata.labels.'app.kubernetes.io/name'
```

To improve this situation, either

1. Quarkus Helm should provide a dedicated boolean for this functionality as this is probably a common use case

2. or `quarkus.helm.expressions.name` should at least support a list of `paths` (YAMLPath expressions) instead of a single `path`, the same as `quarkus.values.name.paths` supports multiple YAMLPath expressions
So it could at least look like this:
```
quarkus:
  helm:
    expressions:
      releaseNamespace:
        expression: "{{ .Release.Namespace }}"
        path: metadata.namespace,(kind == Deployment).spec.template.metadata.namespace
      releaseInstanceName:
        expression: "{{ .Release.Name }}"
        path: metadata.name,metadata.labels.'app.kubernetes.io/name',(kind == Service).spec.selector.'app.kubernetes.io/name',(kind == Deployment).spec.selector.matchLabels.'app.kubernetes.io/name',(kind == Deployment).spec.template.metadata.labels.'app.kubernetes.io/name'
```
