### ISSUE TITLE
Config `quarkus.helm.map-system-properties=true` not working with Gradle

### ISSUE THREAD

**Issue by ThoSap** [quarkiverse/quarkus-helm#335]
[Helm extension for Quarkus - Mapping System Properties](https://docs.quarkiverse.io/quarkus-helm/dev/index.html#mapping-system-properties)

I tried using `quarkus.helm.map-system-properties=true` with
- Quarkus Helm 1.2.3
- Quarkus 3.9.4
  - Quarkus YAML Configuration
- Gradle 8.7
and it seems like in this constellation the HelmProcessor does not seem to pick up the system properties expressions like for example:
```
quarkus:
  grpc:
    clients:
      mdc-grpc-service:
        host: ${GRPC_HOST:my-grpc-service.my-namespace.svc.cluster.local}
        port: ${GRPC_PORT:9000}
        negotiation-type: ${GRPC_NEGOTIATION_TYPE:PLAINTEXT}
        plain-text: ${GRPC_PLAIN_TEXT:true}
        compression: ${GRPC_COMPRESSION:gzip}
  mailer:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    from: ${MAIL_FROM:My Service <my.service@example.com>}
```

I know that this property is enabled by default, I anyways also tried to explicitly add it to the `applications.yaml` and makes no difference.

The generated `values.yaml` and `deployment.yaml` does not contain any of these system properties which should be automatically picked up by Quarkus Helm.

This is probably not related to Quarkus Helm itself, but rather how Quarkus reads such PropertiesConfigSource system properties when Gradle is used as a build system, so I tag @radcortez here.

https://github.com/quarkiverse/quarkus-helm/blob/1.2.3/deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java#L73-L93
https://github.com/quarkiverse/quarkus-helm/blob/1.2.3/deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java#L410-L412
