### ISSUE TITLE
Resource templates not merged, documentation incorrect

### ISSUE THREAD

**Issue by diversit** [quarkiverse/quarkus-helm#385]
While trying to add conditional `imagePullSecrets` to a Deployment, I ran into several issues.
Basically, I would like to be able to add something like
```yaml
  {{- with .Values.imagePullSecret }}
  imagePullSecrets:
    - name: {{ . }}
  {{- end }}
```
so an imagePullSecret gets added to a Deployment depending on whether a `imagePullSecret` is defined in the `values.yaml` or not.
When deploying locally, an imagePullSecret is not required, but when deploying in our test, accept and prod clusters it is.

The issues I ran into:

- When using `quarkus.helm.expressions` to add a `imagePullSecrets` the property would not be added to the resource when the property did not already exist in the resource

With this configuration in the `application.properties`:
```
quarkus.helm.expressions.0.path=(kind == Deployment).spec.template.spec.imagePullSecrets
quarkus.helm.expressions.0.expression={{ .Release.Name }}
```
the `imagePullSecrets` property was never added to the Deployment resource.
Note that the expression `{{ .Release.Name }}` was just a test value.

Only after also adding
```
quarkus.kubernetes.image-pull-secrets=dummy
```
 the Kubernetes extension would add the `imagePullSecrets` property and the Helm extension would then replace it with an expression.
This is not what I expected after reading the documentation.
Why can the Helm extension not just add the property if it does not exist?

- Resources in `src/main/helm/templates` are not merged with the generated output

Based on the example in the section about [Install the Helm dependencies in order](https://docs.quarkiverse.io/quarkus-helm/dev/index.html#helm-dependencies-install-in-order), I thought it would be possible to add a `src/main/helm/templates/deployment.yaml` resource containing

```yaml
{{- with .Values.imagePullSecret }}
imagePullSecrets:
  - name: {{ . }}
{{- end }}
```

or 

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
```
Note: the mentioned folder `src/main/helm/kubernetes/templates` is just wrong as the integration test `helm-kubernetes-with-templates` just stores the templates in `src/main/helm/templates`.
But neither work. Also, trying out the initContainer example in the documentation does not work!

Looking at the source code in `QuarkusHelmWriterSessionListener#processUserDefinedTemplates` explains this behaviour since there it only extracts the template functions from the user-defined-template and just ignores the rest.

Why was chosen to only extract the template functions and not to merge the entire user-defined-template with the generated resource? The `QuarkusHelmWriterSessionListener` class already contains a `mergeWithFileIfExists` function which is now only used for `Chart.yaml`, `values.yaml` etc but not for the user-defined-templates.

Because the Helm extension is not properly using the user-defined-templates in the `src/main/helm/templates` folder, the resulting Helm chart is also not complete enough for use requiring us to use the generate chart only as a base-chart and create a separate Helm chart adding additional resources like NetworkPolicies, Ingress resources, SecretProviderClasses etc.
Similarly, it is now very hard to set the right `securityContext` since the Kubernetes extension also seems to miss settings for `allowPrivilegeEscalation`, `capabilities`, `readOnlyRootFilesystem`, `runAsNonRoot`, etc.

If these are considered bugs or missing features, I would be happy to provide a fix.
What else can I do to conditionally add `imagePullSecrets` to the resulting Deployment resource?
