### ISSUE TITLE
Volumes not correctly mapped

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#46]
Hello!

I have the following property in my application.properties:

```
quarkus.kubernetes.mounts.airflow-dags.path=/opt/airflow/dags
```

which generates the following

in the deployment.yaml at level spec > template > spec > containers 
```
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: airflow-dags
              readOnly: false
```

but we're missing at level spec > template > spec 

```
      volumes:
        - name: airflow-dags
          emptyDir: { }
```

needed for it to work.

The error I get is

```
Error: INSTALLATION FAILED: Deployment.apps "my-service" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "airflow-dags"
```
