### ISSUE TITLE
Service.yaml looks duplicated on version 0.0.4

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#48]
Reproducer: `mvn clean package` over any Quarkus app with Helm extension (Version 0.0.4)

Service.yaml

```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: b288321983d55224d9c0d51d3997c2cd8a98d4db
    app.quarkus.io/build-timestamp: 2022-08-11 - 13:43:55 +0000
  labels:
    app.kubernetes.io/name: examples-quarkus-helm
    app.kubernetes.io/version: v1
  name: examples-quarkus-helm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: examples-quarkus-helm
    app.kubernetes.io/version: v1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: b288321983d55224d9c0d51d3997c2cd8a98d4db
    app.quarkus.io/build-timestamp: 2022-08-11 - 13:43:54 +0000
  labels:
    app.kubernetes.io/name: examples-quarkus-helm
    app.kubernetes.io/version: v1
    app.openshift.io/runtime: quarkus
  name: examples-quarkus-helm
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: examples-quarkus-helm
    app.kubernetes.io/version: v1
  type: ClusterIP

```

This issue is a blocker because doesn't allow me to install the chart. 
Workaround: remove the duplicated service definition by hand
