### ISSUE TITLE
Providing values for a dependency

### ISSUE THREAD

**Issue by antssilva96** [quarkiverse/quarkus-helm#66]
Hello! There might be a way around this that I'm unaware of!

I currently have the following postgres dependency configured in my helm.

```
quarkus.helm.dependencies.postgresql.name=postgresql
quarkus.helm.dependencies.postgresql.version=11.6.22
quarkus.helm.dependencies.postgresql.repository=https://charts.bitnami.com/bitnami
```

And I want to set the following properties for it (see https://github.com/bitnami/charts/tree/master/bitnami/postgresql#global-parameters)

```
global:
  postgresql: 
    auth:
      postgresPassword: secret
      database: my_db_name 
```

Is there any way currently to provide `values.yaml` entries for dependencies ?

Thank you!
