### ISSUE TITLE
Openshift + "non-root containers" doesn't work

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#83]
Quarkus-helm Version: Upstream (0.0.6.snapshot)

When I try to deploy a Quarkus application that has a database as PostgreSQL I am getting the following error: 

```
09:23:27,865 INFO  Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext.runAsUser): invalid type for io.k8s.api.core.v1.SecurityContext.runAsUser: got "string", expected "integer"
```

As a result of this error, PostgreSQL is not deployed. 

By default, OpenShift runs containers as "non-root" containers in order to avoid some security vulnerabilities like do whatever you want in your container, such as install system packages, edit configuration files, bind privilege ports, adjust permissions, create system users and groups, access networking information...etc however Docker by default run the containers as root. 

One common approach in order to make it work (especially in development) is to disable "podSecurityContext", auto-generate a user ID for volume permission etc... 

In my example, I am using Bitnami [PostgreSQL helm chart](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/primary/statefulset.yaml#L130) and the following values.yaml is working in order to deploy a Bitnami database into my OpenShift cluster

PostgresSQL values.yaml

```
postgresql:
  image:
    registry: docker.io
    tag: "13.6"
    repository: library/postgres
  global:
    postgresql:
      auth:
        database: mydb
        password: secret
        postgresPassword: secret
        username: user
  primary:
    podSecurityContext:
      enabled: false
      fsGroup: ""
    containerSecurityContext:
      enabled: false
      runAsUser: ""
    securityContext:
      enabled: false
    volumePermissions:
      securityContext:
        runAsUser: "auto"
      enabled: false
    shmVolume:
      chmod:
        enabled: false
```

So, if I want to deploy a PostgreSQL through helm using Quarkus-helm extension I should have an `application.properties` like this one:

```
# Application properties
quarkus.openshift.route.expose=true
quarkus.container-image.image=quay.io/quarkusqeteam/ts-quarkus-helm-simple-app:v1
quarkus.helm.name=my-chart
quarkus.container-image.builder=docker
quarkus.container-image.build=true
quarkus.container-image.push=true

# dependencies not supported until this patch is released
#TODO https://github.com/quarkiverse/quarkus-helm/issues/66
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.charset=utf-8
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.datasource.username=user
quarkus.datasource.password=secret
quarkus.datasource.jdbc.url=jdbc:postgresql://my-chart-postgresql:5432/mydb

# Helm Database configuration
quarkus.helm.dependencies.postgresql.alias=postgresql
quarkus.helm.dependencies.postgresql.name=postgresql
#Bitnami chart version
quarkus.helm.dependencies.postgresql.version=11.9.1
quarkus.helm.dependencies.postgresql.repository=https://charts.bitnami.com/bitnami

quarkus.helm.values.0.property=postgresql.global.postgresql.auth.postgresPassword
quarkus.helm.values.0.value=secret
quarkus.helm.values.1.property=postgresql.global.postgresql.auth.database
quarkus.helm.values.1.value=mydb
quarkus.helm.values.2.property=postgresql.global.postgresql.auth.password
quarkus.helm.values.2.value=secret
quarkus.helm.values.3.property=postgresql.global.postgresql.auth.username
quarkus.helm.values.3.value=user
quarkus.helm.values.4.property=postgresql.image.tag
quarkus.helm.values.4.value=13.6
quarkus.helm.values.5.property=postgresql.image.repository
quarkus.helm.values.5.value=library/postgres
quarkus.helm.values.6.property=postgresql.image.registry
quarkus.helm.values.6.value=docker.io

quarkus.helm.values.7.property=postgresql.primary.volumePermissions.enabled
quarkus.helm.values.7.value=false
quarkus.helm.values.8.property=postgresql.primary.volumePermissions.securityContext.runAsUser
quarkus.helm.values.8.value="auto"
quarkus.helm.values.9.property=postgresql.primary.securityContext.enabled
quarkus.helm.values.9.value=false
quarkus.helm.values.10.property=postgresql.primary.shmVolume.chmod.enabled
quarkus.helm.values.10.value=false
quarkus.helm.values.11.property=postgresql.primary.containerSecurityContext.enabled
quarkus.helm.values.11.value=false
quarkus.helm.values.12.property=postgresql.primary.containerSecurityContext.runAsUser
quarkus.helm.values.12.value=""
quarkus.helm.values.13.property=postgresql.primary.podSecurityContext.enabled
quarkus.helm.values.13.value=false
#quarkus.helm.values.14.property=postgresql.primary.podSecurityContext.fsGroup
#quarkus.helm.values.14.value=""
```

I am getting some errors with `podSecurityContext.fsGroup` and `containerSecurityContext.runAsUser`(and maybe some other fields) and I can't figure out how to make it work. Also, I could not find any example or doc about how to deploy a non-root container into OpenShift through Quarkus-helm.

This problem is going to be common with most of the containers such as MongoDB, Mysql....etc

**Comment by Sgitario** [comment]
I'm closing this issue because it has nothing to do with the Quarkus Helm extension, but with the bitnami image or maybe with OpenShift.

**Comment by pjgg** [comment]
I saw some different behavior between a pure helm `values.yaml` and Quarkus-helm `application.properties`
In my opinion, we are talking about a mapping issue, let me try to explain you:

These is the generated Helm `values.yaml` by Quarkus-helm

```
app:
  serviceType: ClusterIP
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 0
    httpGet:
      path: /q/health/live
  image: [quay.io/quarkusqeteam/ts-quarkus-helm-simple-app:v1](http://quay.io/quarkusqeteam/ts-quarkus-helm-simple-app:v1)
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 30
    successThreshold: 1
    initialDelaySeconds: 0
    httpGet:
      path: /q/health/ready
postgresql:
  image:
    registry: [docker.io](http://docker.io/)
    tag: "13.6"
    repository: library/postgres
  global:
    postgresql:
      auth:
        database: mydb
        password: secret
        postgresPassword: secret
        username: user
  primary:
    podSecurityContext:
      enabled: "false"
    securityContext:
      enabled: "false"
    containerSecurityContext:
      runAsUser: "0"
      enabled: "false"
    volumePermissions:
      securityContext:
        runAsUser: '"auto"'
      enabled: "false"
    shmVolume:
      chmod:
        enabled: "false"
```

Let's focus on a single property to show up the issue

```
containerSecurityContext:
      runAsUser: "0"
```

This property was generated from this `application.property` value:
```
quarkus.helm.values.12.property=postgresql.primary.containerSecurityContext.runAsUser
quarkus.helm.values.12.value=""
```

And this is what I expect:
```
containerSecurityContext:
      runAsUser: ""
```

The issue is:
 - Who made the decision to use as a user container the user `0` if the developer set this user as ""

Please be sure that the generated `values.yaml` match with the setters values on the `application.properties`
If Quarkus-helm doesn't change the values seted by the developer I think that running a non-root container by this way on OpenShift is going to be possible. But the issue is a mapping issue, "non-running container on OCP" is a side effect.
