### ISSUE TITLE
Wrong field mapping on a custom `values.yaml` - `quarkus.helm.input-directory`

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#85]
Related to: https://github.com/quarkiverse/quarkus-helm/issues/83

When I try to create a Helm chart providing a custom `values.yaml` some fields are not mapped as expected

application.properties
```
quarkus.helm.input-directory=src/main/helm

# Helm Database configuration
quarkus.helm.dependencies.postgresql.alias=postgresql
quarkus.helm.dependencies.postgresql.name=postgresql
#Bitnami chart version
quarkus.helm.dependencies.postgresql.version=11.9.1
quarkus.helm.dependencies.postgresql.repository=https://charts.bitnami.com/bitnami
```

Provided `values.yaml` example
```
postgresql:
  image:
    registry: docker.io
    tag: "13.6"
    repository: library/postgres
  global:
    postgresql:
      auth:
        database: mydb
        password: secret
        postgresPassword: secret
        username: user
  primary:
    volumePermissions:
      securityContext:
        runAsUser: "auto"
      enabled: false
```

Generated `values.yaml`
```
---
postgresql:
  image:
    registry: docker.io
    tag: "13.6"
    repository: library/postgres
  global:
    postgresql:
      auth:
        database: mydb
        password: secret
        postgresPassword: secret
        username: user
  primary:
    volumePermissions:
      securityContext:
        runAsUser: auto
      enabled: false
app:
  serviceType: ClusterIP
  image: quay.io/quarkusqeteam/ts-quarkus-helm-advanced-app:v1

```

The property `volumePermissions.securityContext.runAsUser` should be a String with quotes. 

Generated value:
```
runAsUser: auto
```

Expected
```
runAsUser: "auto"
```
