### ISSUE TITLE
Possible conflicts when using custom templates with probes

### ISSUE THREAD

**Issue by Sgitario** [quarkiverse/quarkus-helm#91]
When using custom templates like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - image: app-image
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP

```

It will fail when processing Helm because the readiness path is `/health/ready`, and the path from Quarkus is by default `/q/health/ready`. The problem is that the extension should filter by the metadata name instead of trying to map all the probes. It needs fixing in Dekorate: https://github.com/dekorateio/dekorate/issues/1065
